### ISSUE TITLE
Class 'therealsmat\Ebulksms\EbulkSmsServiceProvider' not found  

### ISSUE THREAD

**Issue by Adesubomi** [therealSMAT/laravel-ebulksms#1]
After installation and registering `therealsmat\Ebulksms\EbulkSmsServiceProvider::class` in the providers array in **_app.php_**, _artisan_ commands generate an error.

```
Class 'therealsmat\Ebulksms\EbulkSmsServiceProvider' not found 
```

OS - ubuntu0.16.04.1
php: 7.0.22
laravel-framework: 5.5

**Comment by therealSMAT** [comment]
Fixed now. Thanks
